import { ArtStyle } from '@/types';

export const ART_STYLES: ArtStyle[] = [
  {
    id: 'watercolor',
    name: 'Watercolor',
    slug: 'watercolor',
    description: 'Delicate, flowing watercolor painting with soft blending and transparent layers',
    previewImage: '/styles/watercolor.jpg',
    category: 'classic',
    premium: false,
  },
  {
    id: 'oil-painting',
    name: 'Oil Painting',
    slug: 'oil-painting',
    description: 'Rich, textured oil painting with deep colors and visible brushstrokes',
    previewImage: '/styles/oil-painting.jpg',
    category: 'classic',
    premium: false,
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    slug: 'renaissance',
    description: 'Majestic Renaissance portrait in the style of the great masters',
    previewImage: '/styles/renaissance.jpg',
    category: 'classic',
    premium: false,
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    slug: 'pop-art',
    description: 'Bold, vibrant Pop Art style inspired by Warhol and Lichtenstein',
    previewImage: '/styles/pop-art.jpg',
    category: 'modern',
    premium: false,
  },
  {
    id: 'art-nouveau',
    name: 'Art Nouveau',
    slug: 'art-nouveau',
    description: 'Elegant Art Nouveau with organic lines and ornamental details',
    previewImage: '/styles/art-nouveau.jpg',
    category: 'classic',
    premium: false,
  },
  {
    id: 'impressionist',
    name: 'Impressionist',
    slug: 'impressionist',
    description: 'Light-filled Impressionist style with visible brushwork and vibrant colors',
    previewImage: '/styles/impressionist.jpg',
    category: 'classic',
    premium: false,
  },
  {
    id: 'baroque',
    name: 'Baroque',
    slug: 'baroque',
    description: 'Dramatic Baroque portrait with rich chiaroscuro and ornate details',
    previewImage: '/styles/baroque.jpg',
    category: 'classic',
    premium: false,
  },
  {
    id: 'ukiyo-e',
    name: 'Ukiyo-e',
    slug: 'ukiyo-e',
    description: 'Traditional Japanese woodblock print style with flat colors and bold outlines',
    previewImage: '/styles/ukiyo-e.jpg',
    category: 'classic',
    premium: true,
  },
  {
    id: 'minimalist-line',
    name: 'Minimalist Line Art',
    slug: 'minimalist-line',
    description: 'Clean, elegant single-line drawing with minimal detail',
    previewImage: '/styles/minimalist-line.jpg',
    category: 'modern',
    premium: false,
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    slug: 'cyberpunk',
    description: 'Futuristic neon-lit portrait with cyberpunk aesthetics',
    previewImage: '/styles/cyberpunk.jpg',
    category: 'experimental',
    premium: true,
  },
  {
    id: 'vintage-photo',
    name: 'Vintage Photography',
    slug: 'vintage-photo',
    description: 'Classic vintage photograph with sepia tones and film grain',
    previewImage: '/styles/vintage-photo.jpg',
    category: 'modern',
    premium: false,
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    slug: 'art-deco',
    description: 'Geometric Art Deco style with gold accents and symmetrical patterns',
    previewImage: '/styles/art-deco.jpg',
    category: 'classic',
    premium: true,
  },
];
